-- Cloudflare D1 (SQLite) STAGING schema for the Engineering Task Manager.
-- Mirrors the current Supabase tables/columns. This is a STAGING COPY target only —
-- Supabase remains the source of truth. Safe to apply to a fresh D1 DB (uses
-- CREATE TABLE IF NOT EXISTS). Data (re)import is a SEPARATE step
-- (exports/d1/import-staging.sql, generated by scripts/d1/generate-d1-import-sql.mjs)
-- and is destructive to the D1 copy ONLY.

CREATE TABLE IF NOT EXISTS people (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  email       TEXT,
  created_at  TEXT
);

CREATE TABLE IF NOT EXISTS tasks (
  id                    TEXT PRIMARY KEY,
  task_number           INTEGER UNIQUE,
  title                 TEXT NOT NULL,
  description           TEXT,
  notes                 TEXT,
  status                TEXT NOT NULL DEFAULT 'not_started'
                          CHECK (status IN ('not_started','in_progress','on_hold','need_to_review','done')),
  priority              INTEGER NOT NULL DEFAULT 3 CHECK (priority BETWEEN 1 AND 5),
  responsible_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,
  opened_by_person_id   TEXT REFERENCES people(id) ON DELETE SET NULL,
  due_date              TEXT,
  closed_date           TEXT,
  type                  TEXT,
  source_file           TEXT,
  source_page           INTEGER,
  source_raw_text       TEXT,
  import_hash           TEXT,
  archived              INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
  created_at            TEXT,
  updated_at            TEXT
);

CREATE INDEX IF NOT EXISTS idx_tasks_task_number          ON tasks(task_number);
CREATE INDEX IF NOT EXISTS idx_tasks_status               ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority             ON tasks(priority);
CREATE INDEX IF NOT EXISTS idx_tasks_responsible_person   ON tasks(responsible_person_id);
CREATE INDEX IF NOT EXISTS idx_tasks_opened_by_person     ON tasks(opened_by_person_id);
CREATE INDEX IF NOT EXISTS idx_tasks_archived             ON tasks(archived);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date             ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_closed_date          ON tasks(closed_date);
CREATE INDEX IF NOT EXISTS idx_tasks_import_hash          ON tasks(import_hash);

-- Mention notifications backing the "My Mentions" inbox. One row per NEW person mention
-- introduced by a task create/update. Unread = opened_at IS NULL. Identity comes from the
-- lightweight "Current user" selector (NOT authentication). See d1/migrations/
-- 2026-06-25_add_mention_notifications.sql and docs/email-notifications.md.
CREATE TABLE IF NOT EXISTS mention_notifications (
  id                   INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id              TEXT NOT NULL,
  task_number          INTEGER NOT NULL,
  mentioned_person_id  TEXT NOT NULL,
  actor_person_id      TEXT,
  created_at           TEXT NOT NULL,
  opened_at            TEXT,
  source               TEXT NOT NULL DEFAULT 'mention',
  snippet              TEXT
);

CREATE INDEX IF NOT EXISTS idx_mention_notifications_person_unread
  ON mention_notifications(mentioned_person_id, opened_at, created_at);
CREATE INDEX IF NOT EXISTS idx_mention_notifications_task
  ON mention_notifications(task_id);
CREATE INDEX IF NOT EXISTS idx_mention_notifications_actor
  ON mention_notifications(actor_person_id);
